version: '3.8'

services:
  backend:
    image: mini-cis-bs
    build: .
    container_name: mini_cis_bs
    restart: always
    env_file: .env
    ports:
      - "1551:1551"
    volumes:
      - ./assets:/app/assets
    environment:
      - UTC

networks:
  minicis:
    driver: bridge
    external: true