version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mini_cis_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3663:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init-database.sql
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mini_cis
      MYSQL_ROOT_PASSWORD: minicis@2025
      MYSQL_USER: mini_cis
      MYSQL_PASSWORD: minicis@2025
    command: --default-authentication-plugin=mysql_native_password

networks:
  minicis:
    name: minicis
    driver: bridge